# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.5'

services:
  funcionariusapiwebapi:
    image: funcionariusapiwebapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
networks:
  default:
    external:
      name: api-network      