# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.5'

services:
  fdpapiwebapi:
    image: fdpapiwebapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
networks:
  default:
    external:
      name: api-network