FROM microsoft/dotnet:5-aspnetcore:runtime
LABEL version="1.0" maintainer="Rennã e Richard"
WORKDIR /app
COPY ./folha_de_pagamento_api/FDP.API/FDP.API.WebApi/dist
ENTRYPOINT ["dotnet","fdp.api.webapi.dll"]